In [22]:
import tensorflow as tf
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [32]:
def get_data():
    seed = 2
    np.random.seed(seed)
    names = [i for i in range(785)]
    dataset = pd.read_csv('images.csv', names=names)
    X = dataset.loc[:,1:]
    Y = dataset.loc[:,0]
    enc = OneHotEncoder()
    Y = enc.fit_transform(np.array(Y).reshape(-1,1))
    print(Y.toarray())
    # split the data into training (67%) and testing (33%)
    (X_train, X_test, Y_train, Y_test) = train_test_split(X, Y, test_size=0.33, random_state=seed)
    return X_train, X_test, Y_train, Y_test

In [49]:
def predictor():
    X_train, X_test, Y_train, Y_test = get_data()
    print(type(Y_train))
    
    n_pixels = X_train.shape[1]
    
    #neurons
    n_neurons_1 = 512
    n_neurons_2 = 256
    n_neurons_3 = 128
    n_target = 26
    
    #session
    net = tf.InteractiveSession()
    
    #placeholder
    X = tf.placeholder(dtype = tf.float32, shape=[None,n_pixels])
    Y = tf.placeholder(dtype = tf.float32, shape = [None, n_target])
    
    #initializers
    sigma = 1
    weight_init = tf.variance_scaling_initializer(mode = "fan_avg",distribution="uniform",scale=sigma)
    bias_init = tf.zeros_initializer()
    
    #hidden weights
    W_hidden_1 = tf.Variable(weight_init([n_pixels,n_neurons_1]))
    bias_hidden_1 = tf.Variable(bias_init([n_neurons_1]))

In [50]:
predictor()

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
<class 'scipy.sparse.csr.csr_matrix'>


/home/shivam/gitRepos/neuralNetworks/lib/python3.6/site-packages/tensorflow/python/client/session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
